// src/components/ImageView.tsx
import DirEntry from '@/types/DirEntry';
import isEmptyArray from '@/utils/isEmptyArray';
import { Component, ComponentProps, Show, createEffect, createSignal, on, onCleanup } from 'solid-js';
import LoadingSpinners from './LoadingSpinners';
import { convertFileSrc } from '@tauri-apps/api/tauri';

interface ImageViewProps extends ComponentProps<any> {
  images: DirEntry[];
}

const ImageView: Component<ImageViewProps> = (props: ImageViewProps) => {
  const [imageIndex, setImageIndex] = createSignal(0);
  const [scale, setScale] = createSignal(1);

  const upScale = () => scale() < 5 && setScale(scale() + 0.5);
  const downScale = () => scale() > 0.5 && setScale(scale() - 0.5);

  const prevImage = () => imageIndex() > 0 && setImageIndex(imageIndex() - 1);
  const nextImage = () => imageIndex() < props.images.length - 1 && setImageIndex(imageIndex() + 1);

  createEffect(on(imageIndex, () => setScale(1)));
  createEffect(() => {
    props.images
    setImageIndex(0)
  });

  const handleKeyDown = (event: any) => {
    if (event.key === 'ArrowRight') {
      nextImage();
    }

    if (event.key === 'ArrowLeft') {
      prevImage();
    }

    if (event.key === 'ArrowUp') {
      setScale(scale() + 0.5);
    }

    if (event.key === 'ArrowDown') {
      setScale(scale() - 0.5);
    }
  };

  window.addEventListener('keydown', handleKeyDown);

  onCleanup(() => window.removeEventListener('keydown', handleKeyDown));

  return (
    <Show when={!isEmptyArray(props.images)} fallback={<LoadingSpinners />}>
      <>
        <button
          onClick={prevImage}
          disabled={imageIndex() === 0}
          class="absolute disabled:opacity-30 rounded-full p-3 bg-neutral-800/80 z-50 top-1/2 -translate-y-1/2 left-8 text-neutral-50/80"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path
              fill-rule="evenodd"
              d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z"
              clip-rule="evenodd"
            />
          </svg>
        </button>
        <img
          style={{ transform: `scale(${scale()})` }}
          draggable="false"
          class="h-full w-auto object-scale-down select-none transition duration-300 ease-in-out origin-center"
          src={convertFileSrc(props.images[imageIndex()].path)}
        />
        <button
          onClick={nextImage}
          disabled={imageIndex() === props.images.length - 1}
          class="absolute disabled:opacity-30 rounded-full p-3 bg-neutral-800/80 z-50 top-1/2 -translate-y-1/2 right-8 text-neutral-50/80"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path
              fill-rule="evenodd"
              d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
              clip-rule="evenodd"
            />
          </svg>
        </button>
        <div class="absolute top-10 right-8 flex flex-col items-center">
          <button onClick={upScale} class="p-3 text-neutral-50/80">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
              <path d="M9 6a.75.75 0 01.75.75v1.5h1.5a.75.75 0 010 1.5h-1.5v1.5a.75.75 0 01-1.5 0v-1.5h-1.5a.75.75 0 010-1.5h1.5v-1.5A.75.75 0 019 6z" />
              <path
                fill-rule="evenodd"
                d="M2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9zm7-5.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11z"
                clip-rule="evenodd"
              />
            </svg>
          </button>
          <button onClick={downScale} class="p-3 text-neutral-50/80">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
              <path d="M6.75 8.25a.75.75 0 000 1.5h4.5a.75.75 0 000-1.5h-4.5z" />
              <path
                fill-rule="evenodd"
                d="M9 2a7 7 0 104.391 12.452l3.329 3.328a.75.75 0 101.06-1.06l-3.328-3.329A7 7 0 009 2zM3.5 9a5.5 5.5 0 1111 0 5.5 5.5 0 01-11 0z"
                clip-rule="evenodd"
              />
            </svg>
          </button>
        </div>
      </>
    </Show>
  );
};

export default ImageView;

// src/components/ImageView.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch, watchEffect } from 'vue'
import { convertFileSrc, invoke } from '@tauri-apps/api/core'

const props = defineProps<{ folderPath?: string }>()

const imgLoaded = ref(false)
const images = ref<string[]>([])
const currentIndex = ref(0)
const currentProgress = ref(0)
const isPlay = ref(false)
const isDisplayPlayPauseButton = ref(false)

let intervalId: any = null

watchEffect(async () => {
    images.value = await invoke('read_images_dir', {
        folderPath: props.folderPath,
    })
    currentIndex.value = 0
})

watch(currentIndex, () => {
    imgLoaded.value = false
})

watch(currentProgress, () => {
    if (currentProgress.value === 100) {
        next()
        currentProgress.value = 0
    } if (currentIndex.value === images.value.length - 1) {
        clearInterval(intervalId)
        isPlay.value = false
    }
})

watch(isPlay, () => {
    if (isPlay.value && currentIndex.value !== images.value.length - 1) {
        intervalId = setInterval(() => {
            currentProgress.value += 1
        }, 20)
    } else {
        clearInterval(intervalId)
    }
    if (currentIndex.value !== images.value.length - 1) {
        isDisplayPlayPauseButton.value = true
        setTimeout(() => {
            isDisplayPlayPauseButton.value = false
        }, 400)
    }
})

function play() {
    if (images.value.length === 0) return
    if (currentIndex.value !== images.value.length - 1) {
        isPlay.value = !isPlay.value
    }
}

function prev() {
    if (images.value.length === 0) return
    if (currentIndex.value !== 0) {
        currentIndex.value =
            (currentIndex.value - 1 + images.value.length) % images.value.length
    }
}

function next() {
    if (images.value.length === 0) return
    if (currentIndex.value !== images.value.length - 1) {
        currentIndex.value = (currentIndex.value + 1) % images.value.length
    }
}

function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'ArrowLeft') {
        prev()
    } else if (event.key === 'ArrowRight') {
        next()
    } else if (event.key === ' ') {
        play()
    }
}

onMounted(() => {
    window.addEventListener('keydown', handleKeydown)
})

onUnmounted(() => {
    window.removeEventListener('keydown', handleKeydown)
    clearInterval(intervalId)
})
</script>

<template>
    <div class="w-full h-full flex justify-center items-center relative">
        <button @click="play" :class="isDisplayPlayPauseButton ? 'animate-ping' : 'opacity-0'"
            class="absolute top-1/2 z-10 text-neutral-300/70 h-8 w-8 flex justify-center items-center rounded-full bg-[#030609]/30 left-1/2 -translate-x-1/2 -translate-y-1/2">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-3.5"
                :class="isPlay ? '-mr-0.5' : ''">
                <path v-if="isPlay" fill-rule="evenodd"
                    d="M4.5 5.653c0-1.427 1.529-2.33 2.779-1.643l11.54 6.347c1.295.712 1.295 2.573 0 3.286L7.28 19.99c-1.25.687-2.779-.217-2.779-1.643V5.653Z"
                    clip-rule="evenodd" />
                <path v-else fill-rule="evenodd"
                    d="M6.75 5.25a.75.75 0 0 1 .75-.75H9a.75.75 0 0 1 .75.75v13.5a.75.75 0 0 1-.75.75H7.5a.75.75 0 0 1-.75-.75V5.25Zm7.5 0A.75.75 0 0 1 15 4.5h1.5a.75.75 0 0 1 .75.75v13.5a.75.75 0 0 1-.75.75H15a.75.75 0 0 1-.75-.75V5.25Z"
                    clip-rule="evenodd" />
            </svg>
        </button>
        <img @click="play" v-if="images.length > 0" draggable="false"
            class="h-full w-auto object-contain transition duration-300 ease-in-out" :class="imgLoaded
                ? 'opacity-100 blur-0 scale-100'
                : 'opacity-0 blur-md scale-95'
                " :src="convertFileSrc(images[currentIndex])" :key="convertFileSrc(images[currentIndex])"
            @load="imgLoaded = true" />
    </div>
</template>
